### ISSUE TITLE
In place matrix transpose with square, fat and tall matrices

### ISSUE THREAD

**Issue by rayjs** [xianyi/OpenBLAS#1289]
In place transposition (no scaling):
The results seems to be correct for square matrices. For non-square matrices should I simply use `cblas_xomatcopy` as the results below are wrong. Please help me out.

If yes, then `cblas_ximatcopy` should not allow non-square matrices, perhaps?

Here is my function call (row ordered matrix where *.X() is width and *.Y() is height)
 `TensorShape<std::size_t> tshape = tensor.shape();`
    `const int lda = (int)tshape.X(); `
  `  const int ldb = (int)tshape.Y();`

   ` cblas_simatcopy(CBLAS_ORDER::CblasRowMajor, CBLAS_TRANSPOSE::CblasTrans, (int)tshape.Y(), (int)tshape.X(), 1.0f, tensor.buffer(), lda, ldb);`

With square matrices(correct result):
Input:
`Tensor:` {
`Shape(W, H):       [5, 5, ]`

		           0            1            2            3            4 
		           5            6            7            8            9 
		          10           11           12           13           14 
		          15           16           17           18           19 
		          20           21           22           23           24 
} 
Output:

`Tensor:` {
`Shape(W, H):       [5, 5, ]`

		           0            5           10           15           20 
		           1            6           11           16           21 
		           2            7           12           17           22 
		           3            8           13           18           23 
		           4            9           14           19           24 
} 
-----------------------------------------------------------
With fat matrices (wrong result):
Input:
`Tensor:` {
`Shape(W, H):       [5, 3, ]`

		           0            1            2            3            4 
		           5            6            7            8            9 
		          10           11           12           13           14 
} 

Output:
`Tensor: `{
`Shape(W, H):       [3, 5, ]`

		           0            5           10 
		           1            6           11 
		           2            7           12 
		           3            8           11 
		          12           13           14 
} 
--------------------------------------------------
With tall matrices (wrong result):
Input:
`Tensor: `{
`Shape(W, H):       [3, 5, ]`

		           0            1            2 
		           3            4            5 
		           6            7            8 
		           9           10           11 
		          12           13           14 
} 

Output:
`Tensor: `{
`Shape(W, H):       [5, 3, ]`

		           0            3            6            3            4 
		           1            4            7            8            9 
		           2            5            8           13           14 
} 

Thanks

**Comment by martin-frbg** [comment]
Which version of OpenBLAS are you seeing this with ? This bug should be fixed in 0.2.20 (fix was PR #1244, merged July 24)

**Comment by rayjs** [comment]
So, I was using 0.2.18. So I did a git pull and the current version in Changelog.txt is 0.2.20.
I compiled OpenBLAS and linked and ran my test again.

Square matrix- correct result
Fat matrix- incorrect result
Tall matrix- memory deallocation error
------------------------------------------------------------------------------------------------------------
Input:
I did a test with a fat matrix. Result seems to be wrong again.
`Tensor:` {
`Shape(W, H):       [5, 2, ]`

		           0            1            2            3            4 
		           5            6            7            8            9 
} 

Output
`Tensor: `{
`Shape(W, H):       [2, 5, ]`

		           0            5 
		           1            6 
		           2            7 
		           3            7 
		           8            9 
} 
-------------------------------------------------------------------------------------------------------------

With a square matrix (correct result)

Input:
`Tensor: `{
`Shape(W, H):       [5, 5, ]`

		           0            1            2            3            4 
		           5            6            7            8            9 
		          10           11           12           13           14 
		          15           16           17           18           19 
		          20           21           22           23           24 
} 

Output:
`Tensor:` {
`Shape(W, H):       [5, 5, ]`

		           0            5           10           15           20 
		           1            6           11           16           21 
		           2            7           12           17           22 
		           3            8           13           18           23 
		           4            9           14           19           24 
} 

-------------------------------------------------------------------------------------------------------------
With a tall matrix (memory deallocation error)

Input:
`Tensor:` {
`Shape(W, H):       [2, 5, ]`

		           0            1 
		           2            3 
		           4            5 
		           6            7 
		           8            9 
} 



*** Error in `redacted': free(): invalid pointer: 0x0000000001e9f010 ***

**Comment by martin-frbg** [comment]
Meh, seems I committed the correction for complex (zimatcopy.c) only, and the same fix still
needs to be applied in interface/imatcopy.c

**Comment by martin-frbg** [comment]
@rayjs if you could do another "git pull" I believe this should be fixed... though it still lacks the optimizations proposed in #1243

**Comment by rayjs** [comment]
Seems like the same error still exists. Quite different issues for fat and tall matrices as mention above.

**Comment by martin-frbg** [comment]
Indeed, sorry. This suffers not only from the erroneous shortcut, but from the same cols/rows confusion as was recently fixed in zimatcopy as well. I'll do another PR later today.
