### ISSUE TITLE
dgemv_n_BARCELONA segfault  (openblas 0.3.18)

### ISSUE THREAD

**Issue by bchareyre** [xianyi/OpenBLAS#3421]
Hi there,

``
#5  0x00007f6e1d0a3500 in dgemv_n_BARCELONA () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
``
This segfault started to appear in the gitlab CI of yade [1] after an upgrade to libopenblas 0.3.18 in debian 12 bookworm (previous version was 0.3.17 and it was perfectly fine). It is a feature breaker for the yade package.
None of the older OSs gave that crash before. Any idea what the reason could be?
Thanks.

[1] https://gitlab.com/yade-dev/trunk/-/jobs/1675638086#L9746

**Comment by martin-frbg** [comment]
Odd. I am not aware of a change between 0.3.17 and 0.3.18 that would affect dgemv_n on Barcelona. (The only somewhat related change would have been #3318, and that one should not matter on Barcelona target as it involves FMA3 capability). Is the CI job running on actual Barcelona hardware ?

**Comment by cosurgi** [comment]
I checked the hardware used by the CI jobs. Crashes have started to appear on:

1. AMD Opteron(tm) Processor 6180 SE
2. AMD Opteron(TM) Processor 6272

Did not appear on:
1. AMD EPYC 7702P 64-Core Processor

**Comment by martin-frbg** [comment]
EPYC should be using "ZEN" target kernels (mostly equivalent to HASWELL) so probably unaffected, but I really do not think anything changed in 0.3.18 for the old "BARCELONA"-type. Unfortunately I do not possess old AMD hardware, a "TARGET=BARCELONA" build on Haswell-generation Intel passes all my usual tests.

**Comment by cosurgi** [comment]
Could it be a crash due to an unrecognized assembler instruction by the old processor? Maybe some compiler flags targeting an architecture have changed?

**Comment by cosurgi** [comment]
The problem might have actually been introduced between versions  0.3.13 and 0.3.17. [1]

[1] https://gitlab.com/yade-dev/trunk/-/issues/241#note_709488735

**Comment by martin-frbg** [comment]
The only change I am aware of is as mentioned above - different use of `-mfma` for cpus that feature the fma3 extension (which I believe Barcelona does not). Also the dgemv_n kernel for Barcelona is written directly in assembler,and was last touched in 2014.

**Comment by martin-frbg** [comment]
What's the reason for putting the lower cutoff at 0.3.13 ? (There definitely was a serious problem - created by me - in 0.3.16 but that was fixed in 0.3.17. Before that, 0.3.12 fixed poor assembly coding in several gemv kernels but not the one for Barcelona. Of course it is possible that the fault lies in some other part of the code e.g. scribbling in memory but that will be harder to track down.

**Comment by martin-frbg** [comment]
Found a MagnyCours system in the GCC Compile Farm but do not see any problems with the build so far. Can you detail your build options for OpenBLAS (or is that a stock package for Debian12 where I can find the specifications online myself) ? Note I will most iikely not be able to use your Yade build job as reproducer, given the limited resources and non-priviledged account there.

**Comment by brada4** [comment]
backtrace would need at least dbgsym to decode call arguments. without those - you can call BLAS with any values  in pointer arguments and cauae a SEGV. 
REF: https://wiki.debian.org/HowToGetABacktrace

**Comment by cosurgi** [comment]
It is a stock debian package.

**Comment by gladk** [comment]
Just for info. Compilation flags, defined during the openblas-package building in debian are listed [here](https://sources.debian.org/src/openblas/0.3.18+ds-1/debian/rules/). 

@svillemot we are discussing here a possible bug, which visible in Yade package. If you have some more information, please let us know. Thanks.

**Comment by martin-frbg** [comment]
Yes I already found and read the rules file, thank you. So far I see nothing unusual in it, and I still cannot reproduce the dgemv failure on the gccfarm system, with a DYNAMIC_ARCH version of the library built on Haswell. (Using BLAS-Tester fr checking - which is basically the testsuite from ATLAS. The gcc version is older however as the gccfarm machine only has gcc 6.3 and associated libs preinstalled (a Debian 9 system apparently)

**Comment by gladk** [comment]
@cosurgi maybe we can install libopenblas-dbg package on CI with the hope to get some more information during failure?

**Comment by cosurgi** [comment]
@gladk let's try a simple apt install [1] and watch this pipeline [2].

[1] https://gitlab.com/yade-dev/trunk/-/merge_requests/780/commits
[3] https://gitlab.com/yade-dev/trunk/-/jobs/1703717900

EDIT: I had a small mistake in that commit. Let's see now.

**Comment by cosurgi** [comment]
@gladk, I suppose we need to modify `/etc/apt/sources.list` to install it. (it failed: https://gitlab.com/yade-dev/trunk/-/jobs/1703717900 )

**Comment by brada4** [comment]
Yes, you are supposed to enable debug symbols repo or confugure symbol server via env variable.
After ythat we know BLAS call parameters and code line that accessed wrong memory.

**Comment by cosurgi** [comment]
@gladk I need your help to obtain more debug info. Please try to install more debug packages in our MR 780 [1]

However I managed to go through all openblas versions [2] from 3.13 to 3.18, using [3]. The crashes in `dgemv_n_BARCELONA` start to appear in version 3.16, the crash logs however are sill without more debug info, sorry about that:

1. crash log for 3.16 - https://gitlab.com/yade-dev/trunk/-/jobs/1706429112
2. crash log for 3.17 - https://gitlab.com/yade-dev/trunk/-/jobs/1706487575

[1] https://gitlab.com/yade-dev/trunk/-/merge_requests/780
[2] https://gitlab.com/yade-dev/trunk/-/merge_requests/780/commits
[3] https://snapshot.debian.org/package/openblas/

**Comment by cosurgi** [comment]
@brada4 I should have listened earlier to your advice, my apologies. I added `export DEBUGINFOD_URLS="https://debuginfod.debian.net"` and gdb downloaded a lot of symbols.
But still this does not seem like enough?

Please examine this crash log: https://gitlab.com/yade-dev/trunk/-/jobs/1706672647

**Comment by martin-frbg** [comment]
Hmm. I had introduced a potentially serious bug in 0.3.16 (and in the sgemv/dgemv interface code even) but that got found and fixed in 0.3.17 so should not affect later builds. Any chance to find out what the crashing code was trying to calculate besides/before calling DGEMV, i.e. what does DEM-PFV-check.py do in terms of BLAS/LAPACK calls, or is that buried under several layers of boost and numpy ? 
(Ideal course of action would be to use `git bisect` to find the presumed bug in OpenBLAS by building and trying intermediate versions, but I still do not see myself building yade with all its prerequisites on the gccfarm machine.)

**Comment by brada4** [comment]
You did the right variable setup, jost that symbol server is incomplete without openblas symbols, maybe it takes time to propagate from pre-release builds. rel 11 has symbols ready for openblas

**Comment by bchareyre** [comment]
We can confirm [1] that:
1/  the problem starts with 0.3.16
2/ 0.3.17 doesn't seem to fix it

Hard to say precisely what was done just before calling DGEMV, since we couldn't produce debug info yet. There's not only boost/numpy layers, there's mainly several calls to openblas via the SuiteSparse library (openblas is nowhere used directly in yade code).
Beside the calls to Cholmod (all in raw c++) there can be also calls to openblas by numpy functions, but I doubt it can interact.
The only thing I can say for sure is that at least one linear system is solved correctly (with SuiteSparse/Cholmod), then the crash when we try to solve the next one.
I should be able to find out the exact sequence of SuiteSparse calls before the crash if it helps.

[1] https://gitlab.com/yade-dev/trunk/-/issues/241#note_711721300

**Comment by brada4** [comment]
Is there a BLAS function that is NOT called in correct cases? betting on dgemv....

**Comment by martin-frbg** [comment]
the point is that the dgemv kernels for barcelona have not changed recently, and neither did the code path to it (except for my 0.3.16 blunder). I (or BLAS-Tester) can call DGEMV just fine on the gccfarm machine. So it would have to be either a corner case never seen before (was suitesparse updated as well ?) or some other part of the code writing over stack or memory (and I do not see where)

**Comment by gladk** [comment]
Suiteparse was updated also at the beginning of September from [5.8.1 till 5.10.1](https://tracker.debian.org/pkg/suitesparse). Can it potentially be also the reason?

**Comment by cosurgi** [comment]
When I was going through openblas versions 3.13 to 3.18 no other package in the docker image was changed. (EDIT: e.g. all the time there was suitesparse 5.10.1+dfsg-2)

**Comment by cosurgi** [comment]
I just tried suiteparse 5.8.1+dfsg-2 (a rather old version, from August) in combination with openblas 3.18. It also crashes. The [commit](https://gitlab.com/yade-dev/trunk/-/commit/db9e33b0d067435224be93a1b856476d45d39868), the [crash log](https://gitlab.com/yade-dev/trunk/-/jobs/1707041876).

**Comment by cosurgi** [comment]
Does it make sense to go down to even older suitesparse versions?

**Comment by gladk** [comment]
[2020-04-19] suitesparse 1:5.7.2+dfsg-1 MIGRATED to testing 
[2020-08-04] suitesparse 1:5.8.1+dfsg-2 MIGRATED to testing

Maybe just 5.7.2, which was over the year in the archive.

**Comment by cosurgi** [comment]
I went back to suiteparse 5.7.1+dfsg-2 in combination with openblas 3.18. It also crashes. The [commit](https://gitlab.com/yade-dev/trunk/-/commit/01ee2d6ad566f9a76a2f915c9ba7acc0cfe71d4c), the [crash log](https://gitlab.com/yade-dev/trunk/-/jobs/1707089159).

Notabene, at the beginning of the log, if you click "Complete Raw" at top, you can find package versions information and how the version downgrade happened.

Summary of the investigations so far:

|               | suitesparse 5.10.1+dfsg-2 | suitesparse 5.8.1+dfsg-2 | suitesparse 5.7.1+dfsg-2 |
| ------        | ---      | ---      | ---      |
| openblas 3.13 | works    | ?        | ?        |
| openblas 3.14 | works    | ?        | ?        |
| openblas 3.15 | works    | ?        | ?        |
| openblas 3.16 | crash    | ?        | ?        |
| openblas 3.17 | crash    | ?        | ?        |
| openblas 3.18 | crash    | crash    | crash    |

**Comment by martin-frbg** [comment]
sorry, I never intended to send you on a suitesparse version chase - suitesparse calling dgemv with some particular matrix size or data range not adequately covered by my tests was just one of the few possibilities that came to my mind...

**Comment by cosurgi** [comment]
@bchareyre , please confirm as I am not sure, but I think that our test is completely reproducible, to the point that input matrices are always the same.

**Comment by brada4** [comment]
gemv does not have conditional code paths, input without NaN-s should be OK in all cases.

**Comment by martin-frbg** [comment]
Problem reproduced with a QEMU VM, currently bisecting but probable cause already identified (unsafe optimization of TRSV in 0.3.16)

**Comment by bchareyre** [comment]
>please confirm as I am not sure, but I think that our test is completely reproducible, to the point that input matrices are always the same.

@cosurgi, Yes indeed they should be the same (at least on one given OS). Since @martin-frbg is apparently on something, I'll refrain dumping the matrices and solving in a dummy program for now. :)

**Comment by gladk** [comment]
> Problem reproduced with a QEMU VM, currently bisecting but probable cause already identified (unsafe optimization of TRSV in 0.3.16)

If you will have something to test please let us know. We will be able to build a patched packaged version of openblas and test it against Yade. Thanks!

**Comment by brada4** [comment]
If you want to test
https://github.com/xianyi/OpenBLAS/pull/3422

**Comment by martin-frbg** [comment]
Yes, #3422 it is.
